import { EmployeeRow } from './excelService';
import Employee from '../models/Employee';
import bcrypt from 'bcryptjs';

interface ValidationError {
  row: number;
  field: string;
  value: string;
  message: string;
  severity: 'error' | 'warning' | 'info';
}

interface ValidationReport {
  totalRows: number;
  validRows: number;
  errorRows: number;
  warningRows: number;
  autoGenerated: number;
  errors: ValidationError[];
  leavePlanDistribution: Record<string, number>;
}

export class BulkUploadService {
  async validateEmployees(employees: EmployeeRow[]): Promise<ValidationReport> {
    const errors: ValidationError[] = [];
    const validRowIndices = new Set<number>();
    const errorRowIndices = new Set<number>();
    const warningRowIndices = new Set<number>();
    let autoGenerated = 0;
    const leavePlanDistribution: Record<string, number> = {};

    console.log(`Starting validation for ${employees.length} employees`);

    for (let i = 0; i < employees.length; i++) {
      const employee = employees[i];
      const rowNumber = i + 3; // Account for header and sample row

      try {
        // Track leave plan distribution
        if (employee.leavePlan) {
          leavePlanDistribution[employee.leavePlan] = (leavePlanDistribution[employee.leavePlan] || 0) + 1;
        }

      // Required fields validation
      if (!employee.firstName) {
        errors.push({
          row: rowNumber,
          field: 'First Name',
          value: '',
          message: 'First Name is required',
          severity: 'error'
        });
        errorRowIndices.add(rowNumber);
      }

      if (!employee.lastName) {
        errors.push({
          row: rowNumber,
          field: 'Last Name',
          value: '',
          message: 'Last Name is required',
          severity: 'error'
        });
        errorRowIndices.add(rowNumber);
      }

      if (!employee.dateOfBirth) {
        errors.push({
          row: rowNumber,
          field: 'Date of Birth',
          value: '',
          message: 'Date of Birth is required',
          severity: 'error'
        });
        errorRowIndices.add(rowNumber);
      } else {
        // Validate age (must be at least 18)
        const age = this.calculateAge(employee.dateOfBirth);
        if (age < 18) {
          errors.push({
            row: rowNumber,
            field: 'Date of Birth',
            value: employee.dateOfBirth.toString(),
            message: 'Employee must be at least 18 years old',
            severity: 'error'
          });
          errorRowIndices.add(rowNumber);
        }
      }

      if (!employee.gender) {
        errors.push({
          row: rowNumber,
          field: 'Gender',
          value: '',
          message: 'Gender is required',
          severity: 'error'
        });
        errorRowIndices.add(rowNumber);
      } else {
        const validGenders = ['Male', 'Female', 'Other'];
        if (!validGenders.includes(employee.gender)) {
          errors.push({
            row: rowNumber,
            field: 'Gender',
            value: employee.gender,
            message: `Invalid Gender. Must be one of: ${validGenders.join(', ')}`,
            severity: 'error'
          });
          errorRowIndices.add(rowNumber);
        }
      }

      // Employee ID will be auto-generated during processing
      autoGenerated++;

      if (!employee.dateOfJoining) {
        errors.push({
          row: rowNumber,
          field: 'Date of Joining',
          value: '',
          message: 'Date of Joining is required',
          severity: 'error'
        });
        errorRowIndices.add(rowNumber);
      }

      if (!employee.department) {
        errors.push({
          row: rowNumber,
          field: 'Department',
          value: '',
          message: 'Department is required',
          severity: 'error'
        });
        errorRowIndices.add(rowNumber);
      }

      if (!employee.designation) {
        errors.push({
          row: rowNumber,
          field: 'Designation',
          value: '',
          message: 'Designation is required',
          severity: 'error'
        });
        errorRowIndices.add(rowNumber);
      }

      // New required fields
      if (!employee.legalEntity) {
        errors.push({
          row: rowNumber,
          field: 'Legal Entity',
          value: '',
          message: 'Legal Entity is required',
          severity: 'error'
        });
        errorRowIndices.add(rowNumber);
      } else {
        const validEntities = ['Acuvate Software Private Limited', 'Acuvate UK Limited', 'Acuvate Inc. (USA)'];
        if (!validEntities.includes(employee.legalEntity)) {
          errors.push({
            row: rowNumber,
            field: 'Legal Entity',
            value: employee.legalEntity,
            message: `Invalid Legal Entity. Must be one of: ${validEntities.join(', ')}`,
            severity: 'error'
          });
          errorRowIndices.add(rowNumber);
        }
      }

      if (!employee.businessUnit) {
        errors.push({
          row: rowNumber,
          field: 'Business Unit',
          value: '',
          message: 'Business Unit is required',
          severity: 'error'
        });
        errorRowIndices.add(rowNumber);
      } else {
        const validUnits = ['Technology', 'Marketing & Sales', 'Finance & Operations', 'Human Resources'];
        if (!validUnits.includes(employee.businessUnit)) {
          errors.push({
            row: rowNumber,
            field: 'Business Unit',
            value: employee.businessUnit,
            message: `Invalid Business Unit. Must be one of: ${validUnits.join(', ')}`,
            severity: 'error'
          });
          errorRowIndices.add(rowNumber);
        }
      }

      if (!employee.hireType) {
        errors.push({
          row: rowNumber,
          field: 'Hire Type',
          value: '',
          message: 'Hire Type is required',
          severity: 'error'
        });
        errorRowIndices.add(rowNumber);
      } else {
        const validHireTypes = ['Contract', 'Permanent', 'Intern', 'Management'];
        if (!validHireTypes.includes(employee.hireType)) {
          errors.push({
            row: rowNumber,
            field: 'Hire Type',
            value: employee.hireType,
            message: `Invalid Hire Type. Must be one of: ${validHireTypes.join(', ')}`,
            severity: 'error'
          });
          errorRowIndices.add(rowNumber);
        }
      }

      if (!employee.location) {
        errors.push({
          row: rowNumber,
          field: 'Location',
          value: '',
          message: 'Location is required',
          severity: 'error'
        });
        errorRowIndices.add(rowNumber);
      }

      if (!employee.workerType) {
        errors.push({
          row: rowNumber,
          field: 'Worker Type',
          value: '',
          message: 'Worker Type is required',
          severity: 'error'
        });
        errorRowIndices.add(rowNumber);
      } else {
        const validWorkerTypes = ['Permanent', 'Full-Time', 'Part-Time', 'Contract', 'Intern', 'Management'];
        if (!validWorkerTypes.includes(employee.workerType)) {
          errors.push({
            row: rowNumber,
            field: 'Worker Type',
            value: employee.workerType,
            message: `Invalid Worker Type. Must be one of: ${validWorkerTypes.join(', ')}`,
            severity: 'error'
          });
          errorRowIndices.add(rowNumber);
        }
      }

      // Leave Plan validation - Required field (matches form)
      if (!employee.leavePlan) {
        errors.push({
          row: rowNumber,
          field: 'Leave Plan',
          value: '',
          message: 'Leave Plan is required',
          severity: 'error'
        });
        errorRowIndices.add(rowNumber);
      } else {
        const validPlans = ['Probation', 'Acuvate', 'Confirmation', 'Consultant', 'UK'];
        if (!validPlans.includes(employee.leavePlan)) {
          errors.push({
            row: rowNumber,
            field: 'Leave Plan',
            value: employee.leavePlan,
            message: `Invalid Leave Plan. Must be one of: ${validPlans.join(', ')}`,
            severity: 'error'
          });
          errorRowIndices.add(rowNumber);
        }
      }

      // Holiday Plan validation - Required field
      if (!employee.holidayPlan) {
        errors.push({
          row: rowNumber,
          field: 'Holiday Plan',
          value: '',
          message: 'Holiday Plan is required',
          severity: 'error'
        });
        errorRowIndices.add(rowNumber);
      } else {
        const validHolidayPlans = ['India', 'USA', 'UK', 'Remote'];
        if (!validHolidayPlans.includes(employee.holidayPlan)) {
          errors.push({
            row: rowNumber,
            field: 'Holiday Plan',
            value: employee.holidayPlan,
            message: `Invalid Holiday Plan. Must be one of: ${validHolidayPlans.join(', ')}`,
            severity: 'error'
          });
          errorRowIndices.add(rowNumber);
        }
      }

      // Email validation (official email now required)
      if (!employee.email) {
        errors.push({
          row: rowNumber,
          field: 'Email',
          value: '',
          message: 'Email is required',
          severity: 'error'
        });
        errorRowIndices.add(rowNumber);
      } else {
        if (!this.isValidEmail(employee.email)) {
          errors.push({
            row: rowNumber,
            field: 'Email',
            value: employee.email,
            message: 'Invalid email format',
            severity: 'error'
          });
          errorRowIndices.add(rowNumber);
        } else {
          // Check for duplicate email in database
          try {
            const existingEmail = await Employee.findOne({ 
              $or: [
                { email: employee.email },
                { officialEmail: employee.email }
              ]
            });
            if (existingEmail) {
              errors.push({
                row: rowNumber,
                field: 'Email',
                value: employee.email,
                message: 'Email already exists in database',
                severity: 'error'
              });
              errorRowIndices.add(rowNumber);
            }
          } catch (dbError) {
            console.error('Database error checking email:', dbError);
          }
        }
      }

      // Personal email validation (optional)
      if (employee.personalEmail && !this.isValidEmail(employee.personalEmail)) {
        errors.push({
          row: rowNumber,
          field: 'Personal Email',
          value: employee.personalEmail,
          message: 'Invalid email format',
          severity: 'warning'
        });
        warningRowIndices.add(rowNumber);
      }

      // PAN validation (if provided) - Changed from Tax ID format based on location
      if (employee.panNumber) {
        if (!/^[A-Z]{5}[0-9]{4}[A-Z]$/.test(employee.panNumber)) {
          errors.push({
            row: rowNumber,
            field: 'PAN Number',
            value: employee.panNumber,
            message: 'Invalid PAN format (should be ABCDE1234F)',
            severity: 'error'
          });
          errorRowIndices.add(rowNumber);
        } else {
          // Check for duplicate PAN
          try {
            const existingPan = await Employee.findOne({ panNumber: employee.panNumber });
            if (existingPan) {
              errors.push({
                row: rowNumber,
                field: 'PAN Number',
                value: employee.panNumber,
                message: 'PAN Number already exists in database',
                severity: 'error'
              });
              errorRowIndices.add(rowNumber);
            }
          } catch (dbError) {
            console.error('Database error checking PAN:', dbError);
          }
        }
      }

      // Check if row has no errors
      if (!errorRowIndices.has(rowNumber)) {
        validRowIndices.add(rowNumber);
      }
    } catch (rowError: any) {
        console.error(`Error validating row ${rowNumber}:`, rowError);
        errors.push({
          row: rowNumber,
          field: 'General',
          value: '',
          message: `Validation error: ${rowError.message}`,
          severity: 'error'
        });
        errorRowIndices.add(rowNumber);
      }
    }

    console.log(`Validation complete: ${validRowIndices.size} valid, ${errorRowIndices.size} errors`);

    return {
      totalRows: employees.length,
      validRows: validRowIndices.size,
      errorRows: errorRowIndices.size,
      warningRows: warningRowIndices.size,
      autoGenerated,
      errors,
      leavePlanDistribution
    };
  }

  async processEmployees(employees: EmployeeRow[], onProgress?: (current: number, total: number, employeeName: string) => void): Promise<void> {
    const validEmployees = await this.filterValidEmployees(employees);

    for (let i = 0; i < validEmployees.length; i++) {
      const employee = validEmployees[i];
      
      // Generate Employee ID if not provided (based on hire type)
      let generatedEmployeeId = await this.generateEmployeeId(employee.hireType);

      // Generate display name and name from employee data
      const nameParts = [employee.firstName, employee.middleName, employee.lastName].filter(Boolean);
      const fullName = nameParts.join(' ');
      const displayName = fullName;

      // Generate default password from provided password or use default
      const defaultPassword = employee.password 
        ? await bcrypt.hash(employee.password, 10)
        : await bcrypt.hash('Welcome@123', 10);

      // Map Excel fields to Employee model fields (matches Add Employee form)
      const employeeData: any = {
        // Step 1: Basic Information
        employeeId: generatedEmployeeId,
        name: fullName, // REQUIRED field for Employee model
        displayName: displayName,
        firstName: employee.firstName,
        middleName: employee.middleName,
        lastName: employee.lastName,
        email: employee.email,
        officialEmail: employee.email,
        gender: employee.gender,
        dateOfBirth: employee.dateOfBirth ? employee.dateOfBirth.toISOString().split('T')[0] : undefined,
        
        // Step 2: Employment Details
        dateOfJoining: employee.dateOfJoining ? employee.dateOfJoining.toISOString().split('T')[0] : undefined,
        contractEndDate: employee.contractEndDate ? employee.contractEndDate.toISOString().split('T')[0] : undefined,
        legalEntity: employee.legalEntity,
        designation: employee.designation,
        department: employee.department,
        subDepartment: employee.subDepartment,
        businessUnit: employee.businessUnit,
        location: employee.location,
        hireType: employee.hireType,
        workerType: employee.workerType,
        leavePlan: employee.leavePlan,
        role: 'EMPLOYEE', // Default role
        status: 'active',
        hasLoginAccess: true,
        isActive: true,
        
        // Step 3: Contact Information
        workPhone: employee.workPhone,
        residenceNumber: employee.residenceNumber,
        personalEmail: employee.personalEmail,
        
        // Step 4: Family & Personal Details
        maritalStatus: employee.maritalStatus,
        marriageDate: employee.marriageDate ? employee.marriageDate.toISOString().split('T')[0] : undefined,
        fatherName: employee.fatherName,
        motherName: employee.motherName,
        spouseName: employee.spouseName,
        spouseGender: employee.spouseGender,
        physicallyHandicapped: employee.physicallyHandicapped === 'Yes',
        bloodGroup: employee.bloodGroup,
        nationality: employee.nationality || 'Indian',
        
        // Step 5: Tax ID Details (PAN/SSN/NIN)
        panNumber: employee.panNumber,
        fullNameAsPerPAN: employee.fullNameAsPerPAN,
        
        // Step 6: Bank Details
        salaryPaymentMode: employee.salaryPaymentMode || 'Bank Transfer',
        bankName: employee.bankName,
        accountNumber: employee.accountNumber,
        ifscCode: employee.ifscCode,
        nameOnAccount: employee.nameOnAccount,
        branch: employee.branch,
        
        // System fields
        password: defaultPassword,
        createdAt: new Date(),
        updatedAt: new Date()
      };

      // Remove undefined values
      Object.keys(employeeData).forEach(key => {
        if (employeeData[key] === undefined) {
          delete employeeData[key];
        }
      });

      // Create employee record
      await Employee.create(employeeData);

      // Report progress
      if (onProgress) {
        onProgress(i + 1, validEmployees.length, `${employee.firstName} ${employee.lastName}`);
      }
    }
  }

  private async filterValidEmployees(employees: EmployeeRow[]): Promise<EmployeeRow[]> {
    const report = await this.validateEmployees(employees);
    
    // Return only employees without errors
    const validEmployees: EmployeeRow[] = [];
    for (let i = 0; i < employees.length; i++) {
      const rowNumber = i + 3;
      const hasError = report.errors.some(e => e.row === rowNumber && e.severity === 'error');
      if (!hasError) {
        validEmployees.push(employees[i]);
      }
    }
    
    return validEmployees;
  }

  private async generateEmployeeId(hireType?: string): Promise<string> {
    try {
      // Map hire type to prefix - SAME AS ADD EMPLOYEE FORM
      const prefixMap: { [key: string]: string } = {
        'Contract': 'ACUC',       // ACUvate Contract
        'Permanent': 'ACUA',      // ACUvate (Permanent)
        'Full-Time': 'ACUA',      // Map Full-Time to Permanent
        'Part-Time': 'ACUA',      // Map Part-Time to Permanent
        'Intern': 'ACUI',         // ACUvate Intern
        'Management': 'ACUM',     // ACUvate Management
        'Consultant': 'ACUC',     // Map Consultant to Contract
      };
      
      const prefix = prefixMap[hireType || 'Permanent'] || 'ACUA'; // Default to Permanent
      
      // Find the last employee with this prefix
      const lastEmployee = await Employee.findOne({
        employeeId: { $regex: `^${prefix}` }
      })
      .sort({ employeeId: -1 }) // Sort descending to get highest number
      .select('employeeId')
      .lean();
      
      let sequenceNumber = 1;
      
      if (lastEmployee && lastEmployee.employeeId) {
        // Extract number from ID (e.g., "ACUC0005" → 5)
        const lastId = lastEmployee.employeeId;
        const numberPart = lastId.replace(prefix, ''); // Remove prefix
        const lastSequence = parseInt(numberPart, 10);
        
        if (!isNaN(lastSequence)) {
          sequenceNumber = lastSequence + 1;
        }
      }
      
      // Pad with zeros to make 4 digits (0001, 0002, ..., 9999)
      const paddedNumber = sequenceNumber.toString().padStart(4, '0');
      
      return `${prefix}${paddedNumber}`;
      
    } catch (error) {
      console.error('Error generating employee ID:', error);
      // Fallback to default if error occurs
      return 'ACUA0001';
    }
  }

  private isValidEmail(email: string): boolean {
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    return emailRegex.test(email);
  }

  private calculateAge(dateOfBirth: Date): number {
    const today = new Date();
    const birthDate = new Date(dateOfBirth);
    let age = today.getFullYear() - birthDate.getFullYear();
    const monthDiff = today.getMonth() - birthDate.getMonth();
    
    if (monthDiff < 0 || (monthDiff === 0 && today.getDate() < birthDate.getDate())) {
      age--;
    }
    
    return age;
  }
}

export const bulkUploadService = new BulkUploadService();
