import { useState } from 'react';
import { Sheet, SheetContent, SheetHeader, SheetBody, SheetFooter, SheetTitle, SheetDescription, SheetCloseButton } from '@/components/ui/sheet';

const API_BASE = import.meta.env.VITE_API_URL || 'http://localhost:5000/api';
import { Button } from '@/components/ui/button';
import { Progress } from '@/components/ui/progress';
import { Download, Upload, FileSpreadsheet, AlertCircle, CheckCircle2, XCircle, Users } from 'lucide-react';
import { toast } from 'sonner';
import { cn } from '@/lib/utils';

interface BulkUploadModalProps {
  open: boolean;
  onClose: () => void;
  onSuccess?: () => void;
}

interface ValidationError {
  row: number;
  field: string;
  value: string;
  message: string;
  severity: 'error' | 'warning' | 'info';
}

interface ValidationReport {
  totalRows: number;
  validRows: number;
  errorRows: number;
  warningRows: number;
  autoGenerated: number;
  errors: ValidationError[];
  leavePlanDistribution: Record<string, number>;
}

export function BulkUploadModal({ open, onClose, onSuccess }: BulkUploadModalProps) {
  const [step, setStep] = useState<'upload' | 'validating' | 'report' | 'processing' | 'complete'>('upload');
  const [selectedFile, setSelectedFile] = useState<File | null>(null);
  const [dragActive, setDragActive] = useState(false);
  const [progress, setProgress] = useState(0);
  const [validationReport, setValidationReport] = useState<ValidationReport | null>(null);
  const [processingStatus, setProcessingStatus] = useState({ created: 0, total: 0, current: '' });

  const handleDownloadTemplate = async () => {
    try {
      const response = await fetch(`${API_BASE}/employees/bulk-upload/template`, {
        method: 'GET',
      });
      
      if (!response.ok) throw new Error('Failed to download template');
      
      const blob = await response.blob();
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = 'Employee_Bulk_Upload_Template.xlsx';
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
      document.body.removeChild(a);
      
      toast.success('Template downloaded successfully');
    } catch (error) {
      console.error('Download error:', error);
      toast.error('Failed to download template');
    }
  };

  const handleDrag = (e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    if (e.type === 'dragenter' || e.type === 'dragover') {
      setDragActive(true);
    } else if (e.type === 'dragleave') {
      setDragActive(false);
    }
  };

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    setDragActive(false);
    
    if (e.dataTransfer.files && e.dataTransfer.files[0]) {
      handleFileSelect(e.dataTransfer.files[0]);
    }
  };

  const handleFileInput = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      handleFileSelect(e.target.files[0]);
    }
  };

  const handleFileSelect = (file: File) => {
    // Validate file type
    const validTypes = [
      'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      'application/vnd.ms-excel'
    ];
    
    if (!validTypes.includes(file.type)) {
      toast.error('Invalid file type. Please upload .xlsx file');
      return;
    }
    
    // Validate file size (5MB)
    if (file.size > 5 * 1024 * 1024) {
      toast.error('File size exceeds 5MB limit');
      return;
    }
    
    setSelectedFile(file);
    toast.success('File selected successfully');
  };

  const handleUploadAndValidate = async () => {
    if (!selectedFile) return;
    
    setStep('validating');
    setProgress(0);
    
    const formData = new FormData();
    formData.append('file', selectedFile);
    
    try {
      // Simulate progress
      const progressInterval = setInterval(() => {
        setProgress(prev => Math.min(prev + 10, 90));
      }, 200);
      
      const response = await fetch(`${API_BASE}/employees/bulk-upload/validate`, {
        method: 'POST',
        body: formData,
      });
      
      clearInterval(progressInterval);
      setProgress(100);
      
      if (!response.ok) {
        const errorData = await response.json().catch(() => ({ error: 'Unknown error' }));
        throw new Error(errorData.error || 'Validation failed');
      }
      
      const report: ValidationReport = await response.json();
      setValidationReport(report);
      setStep('report');
      
      if (report.errorRows === 0) {
        toast.success(`All ${report.validRows} employees validated successfully!`);
      } else {
        toast.warning(`${report.validRows} valid, ${report.errorRows} errors found`);
      }
    } catch (error: any) {
      console.error('Validation error:', error);
      toast.error(error.message || 'Failed to validate file');
      setStep('upload');
    }
  };

  const handleProcessEmployees = async () => {
    if (!selectedFile || !validationReport) return;
    
    setStep('processing');
    setProgress(0);
    
    const formData = new FormData();
    formData.append('file', selectedFile);
    
    try {
      const response = await fetch(`${API_BASE}/employees/bulk-upload/process`, {
        method: 'POST',
        body: formData,
      });
      
      if (!response.ok) {
        const errorData = await response.json().catch(() => ({}));
        throw new Error(errorData.error || `Processing failed with status ${response.status}`);
      }
      
      const reader = response.body?.getReader();
      const decoder = new TextDecoder();
      
      if (reader) {
        while (true) {
          const { done, value } = await reader.read();
          if (done) break;
          
          const chunk = decoder.decode(value);
          const lines = chunk.split('\n').filter(Boolean);
          
          for (const line of lines) {
            if (line.startsWith('data: ')) {
              const data = JSON.parse(line.slice(6));
              
              // Check if there's an error in the stream
              if (data.error) {
                throw new Error(data.error);
              }
              
              setProcessingStatus(data);
              setProgress((data.created / data.total) * 100);
            }
          }
        }
      }
      
      setStep('complete');
      toast.success('Employees created successfully!');
      onSuccess?.();
    } catch (error: any) {
      console.error('Processing error:', error);
      toast.error(error?.message || 'Failed to process employees');
      setStep('report');
    }
  };

  const handleClose = () => {
    setStep('upload');
    setSelectedFile(null);
    setValidationReport(null);
    setProgress(0);
    onClose();
  };

  const getSeverityIcon = (severity: 'error' | 'warning' | 'info') => {
    switch (severity) {
      case 'error':
        return <XCircle className="h-4 w-4 text-destructive" />;
      case 'warning':
        return <AlertCircle className="h-4 w-4 text-yellow-600" />;
      case 'info':
        return <CheckCircle2 className="h-4 w-4 text-blue-600" />;
    }
  };

  return (
    <Sheet open={open} onOpenChange={handleClose}>
      <SheetContent className="w-full sm:max-w-4xl p-0">
        <SheetHeader>
          <div className="flex-1">
            <SheetTitle className="flex items-center gap-2">
              <Upload className="h-5 w-5" />
              Employee Bulk Upload
            </SheetTitle>
            <SheetDescription>
              Upload multiple employees at once using Excel template
            </SheetDescription>
          </div>
          <SheetCloseButton />
        </SheetHeader>

        <SheetBody>
          <div className="space-y-6">
            {/* Step Indicator */}
            <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <div className={cn(
                "flex items-center justify-center w-8 h-8 rounded-full text-sm font-medium",
                step === 'upload' ? "bg-primary text-primary-foreground" : "bg-muted text-muted-foreground"
              )}>
                1
              </div>
              <span className="text-sm">Upload</span>
            </div>
            <div className="flex-1 h-px bg-border mx-2" />
            <div className="flex items-center gap-2">
              <div className={cn(
                "flex items-center justify-center w-8 h-8 rounded-full text-sm font-medium",
                ['validating', 'report'].includes(step) ? "bg-primary text-primary-foreground" : "bg-muted text-muted-foreground"
              )}>
                2
              </div>
              <span className="text-sm">Validate</span>
            </div>
            <div className="flex-1 h-px bg-border mx-2" />
            <div className="flex items-center gap-2">
              <div className={cn(
                "flex items-center justify-center w-8 h-8 rounded-full text-sm font-medium",
                ['processing', 'complete'].includes(step) ? "bg-primary text-primary-foreground" : "bg-muted text-muted-foreground"
              )}>
                3
              </div>
              <span className="text-sm">Process</span>
            </div>
          </div>

          {/* Step 1: Upload */}
          {step === 'upload' && (
            <div className="space-y-6">
              {/* Download Template */}
              <div className="border rounded-lg p-6 bg-muted/30">
                <div className="flex items-start gap-4">
                  <div className="p-3 bg-primary/10 rounded-lg">
                    <Download className="h-6 w-6 text-primary" />
                  </div>
                  <div className="flex-1">
                    <h3 className="font-semibold mb-2">Step 1: Download Template</h3>
                    <p className="text-sm text-muted-foreground mb-4">
                      Download the Excel template with all required fields, validations, and instructions.
                    </p>
                    <div className="flex flex-wrap gap-2 text-xs text-muted-foreground mb-4">
                      <span className="flex items-center gap-1">
                        <CheckCircle2 className="h-3 w-3" />
                        49 fields matching form
                      </span>
                      <span className="flex items-center gap-1">
                        <CheckCircle2 className="h-3 w-3" />
                        Data validations
                      </span>
                      <span className="flex items-center gap-1">
                        <CheckCircle2 className="h-3 w-3" />
                        Sample data
                      </span>
                      <span className="flex items-center gap-1">
                        <CheckCircle2 className="h-3 w-3" />
                        Instructions
                      </span>
                    </div>
                    <Button onClick={handleDownloadTemplate} variant="default">
                      <Download className="h-4 w-4 mr-2" />
                      Download Excel Template
                    </Button>
                  </div>
                </div>
              </div>

              {/* Upload File */}
              <div className="border rounded-lg p-6">
                <div className="flex items-start gap-4 mb-4">
                  <div className="p-3 bg-primary/10 rounded-lg">
                    <Upload className="h-6 w-6 text-primary" />
                  </div>
                  <div className="flex-1">
                    <h3 className="font-semibold mb-2">Step 2: Upload Filled Template</h3>
                    <p className="text-sm text-muted-foreground">
                      Select the Excel file with employee data to upload and validate.
                    </p>
                  </div>
                </div>

                {/* Drag & Drop Area */}
                <div
                  className={cn(
                    "border-2 border-dashed rounded-lg p-8 text-center transition-colors",
                    dragActive ? "border-primary bg-primary/5" : "border-border",
                    selectedFile && "bg-muted/50"
                  )}
                  onDragEnter={handleDrag}
                  onDragLeave={handleDrag}
                  onDragOver={handleDrag}
                  onDrop={handleDrop}
                >
                  {selectedFile ? (
                    <div className="space-y-4">
                      <div className="flex items-center justify-center">
                        <FileSpreadsheet className="h-16 w-16 text-green-600" />
                      </div>
                      <div>
                        <p className="font-medium">{selectedFile.name}</p>
                        <p className="text-sm text-muted-foreground">
                          {(selectedFile.size / 1024).toFixed(2)} KB
                        </p>
                      </div>
                      <Button
                        variant="outline"
                        size="sm"
                        onClick={() => setSelectedFile(null)}
                      >
                        Remove File
                      </Button>
                    </div>
                  ) : (
                    <div className="space-y-4">
                      <div className="flex items-center justify-center">
                        <FileSpreadsheet className="h-16 w-16 text-muted-foreground" />
                      </div>
                      <div>
                        <p className="font-medium mb-1">Drag & Drop Excel file here</p>
                        <p className="text-sm text-muted-foreground mb-4">or</p>
                        <label htmlFor="file-upload">
                          <Button variant="outline" asChild>
                            <span>
                              <Upload className="h-4 w-4 mr-2" />
                              Browse Files
                            </span>
                          </Button>
                          <input
                            id="file-upload"
                            type="file"
                            className="hidden"
                            accept=".xlsx,.xls"
                            onChange={handleFileInput}
                          />
                        </label>
                      </div>
                      <div className="text-xs text-muted-foreground">
                        Supported: .xlsx | Max Size: 5MB | Max Rows: 1000
                      </div>
                    </div>
                  )}
                </div>

                {selectedFile && (
                  <div className="mt-4 flex justify-end">
                    <Button onClick={handleUploadAndValidate}>
                      <Upload className="h-4 w-4 mr-2" />
                      Upload & Validate
                    </Button>
                  </div>
                )}
              </div>
            </div>
          )}

          {/* Step 2: Validating */}
          {step === 'validating' && (
            <div className="space-y-6">
              <div className="border rounded-lg p-8 text-center">
                <div className="flex items-center justify-center mb-4">
                  <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary"></div>
                </div>
                <h3 className="font-semibold mb-2">Validating Data...</h3>
                <p className="text-sm text-muted-foreground mb-4">
                  Please wait while we validate the uploaded data
                </p>
                <Progress value={progress} className="w-full max-w-md mx-auto" />
                <p className="text-xs text-muted-foreground mt-2">{progress}%</p>
              </div>
            </div>
          )}

          {/* Step 3: Validation Report */}
          {step === 'report' && validationReport && (
            <div className="space-y-6">
              {/* Summary Cards */}
              <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                <div className="border rounded-lg p-4 bg-green-50 dark:bg-green-950">
                  <div className="text-2xl font-bold text-green-700 dark:text-green-400">
                    {validationReport.validRows}
                  </div>
                  <div className="text-sm text-muted-foreground">Valid Rows</div>
                </div>
                <div className="border rounded-lg p-4 bg-red-50 dark:bg-red-950">
                  <div className="text-2xl font-bold text-red-700 dark:text-red-400">
                    {validationReport.errorRows}
                  </div>
                  <div className="text-sm text-muted-foreground">Errors</div>
                </div>
                <div className="border rounded-lg p-4 bg-yellow-50 dark:bg-yellow-950">
                  <div className="text-2xl font-bold text-yellow-700 dark:text-yellow-400">
                    {validationReport.warningRows}
                  </div>
                  <div className="text-sm text-muted-foreground">Warnings</div>
                </div>
                <div className="border rounded-lg p-4 bg-blue-50 dark:bg-blue-950">
                  <div className="text-2xl font-bold text-blue-700 dark:text-blue-400">
                    {validationReport.autoGenerated}
                  </div>
                  <div className="text-sm text-muted-foreground">Auto-Generated</div>
                </div>
              </div>

              {/* Leave Plan Distribution */}
              <div className="border rounded-lg p-4">
                <h3 className="font-semibold mb-3 flex items-center gap-2">
                  <Users className="h-4 w-4" />
                  Leave Plan Distribution
                </h3>
                <div className="space-y-2">
                  {Object.entries(validationReport.leavePlanDistribution).map(([plan, count]) => (
                    <div key={plan} className="flex items-center justify-between text-sm">
                      <span>{plan}</span>
                      <span className="font-medium">{count}</span>
                    </div>
                  ))}
                </div>
              </div>

              {/* Errors List */}
              {validationReport.errors.length > 0 && (
                <div className="border rounded-lg p-4 max-h-96 overflow-y-auto">
                  <h3 className="font-semibold mb-3 flex items-center gap-2">
                    <AlertCircle className="h-4 w-4" />
                    Validation Issues ({validationReport.errors.length})
                  </h3>
                  <div className="space-y-2">
                    {validationReport.errors.slice(0, 50).map((error, idx) => (
                      <div
                        key={idx}
                        className={cn(
                          "p-3 rounded-lg border text-sm",
                          error.severity === 'error' && "bg-red-50 dark:bg-red-950 border-red-200 dark:border-red-800",
                          error.severity === 'warning' && "bg-yellow-50 dark:bg-yellow-950 border-yellow-200 dark:border-yellow-800",
                          error.severity === 'info' && "bg-blue-50 dark:bg-blue-950 border-blue-200 dark:border-blue-800"
                        )}
                      >
                        <div className="flex items-start gap-2">
                          {getSeverityIcon(error.severity)}
                          <div className="flex-1">
                            <div className="font-medium">Row {error.row}</div>
                            <div className="text-muted-foreground">
                              {error.field}: {error.message}
                            </div>
                            {error.value && (
                              <div className="text-xs mt-1 text-muted-foreground">
                                Current value: "{error.value}"
                              </div>
                            )}
                          </div>
                        </div>
                      </div>
                    ))}
                    {validationReport.errors.length > 50 && (
                      <p className="text-sm text-muted-foreground text-center py-2">
                        ... and {validationReport.errors.length - 50} more issues
                      </p>
                    )}
                  </div>
                </div>
              )}

              {/* Actions */}
              <div className="flex items-center justify-between gap-4 pt-4 border-t">
                <div className="flex gap-2">
                  <Button variant="outline" onClick={() => setStep('upload')}>
                    <Upload className="h-4 w-4 mr-2" />
                    Upload New File
                  </Button>
                </div>
                <div className="flex gap-2">
                  {validationReport.validRows > 0 && (
                    <Button onClick={handleProcessEmployees}>
                      Create {validationReport.validRows} Employees
                    </Button>
                  )}
                </div>
              </div>
            </div>
          )}

          {/* Step 4: Processing */}
          {step === 'processing' && (
            <div className="space-y-6">
              <div className="border rounded-lg p-8 text-center">
                <div className="flex items-center justify-center mb-4">
                  <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary"></div>
                </div>
                <h3 className="font-semibold mb-2">Creating Employees...</h3>
                <p className="text-sm text-muted-foreground mb-4">
                  Processing {processingStatus.current}
                </p>
                <Progress value={progress} className="w-full max-w-md mx-auto" />
                <p className="text-xs text-muted-foreground mt-2">
                  {processingStatus.created} of {processingStatus.total} created
                </p>
              </div>
            </div>
          )}

          {/* Step 5: Complete */}
          {step === 'complete' && (
            <div className="space-y-6">
              <div className="border rounded-lg p-8 text-center bg-green-50 dark:bg-green-950">
                <div className="flex items-center justify-center mb-4">
                  <CheckCircle2 className="h-16 w-16 text-green-600" />
                </div>
                <h3 className="font-semibold text-xl mb-2">Upload Completed!</h3>
                <p className="text-sm text-muted-foreground mb-4">
                  {processingStatus.created} employees have been created successfully
                </p>
                <div className="flex justify-center gap-4">
                  <Button onClick={handleClose} variant="outline">
                    Close
                  </Button>
                  <Button onClick={() => {
                    setStep('upload');
                    setSelectedFile(null);
                    setValidationReport(null);
                  }}>
                    Upload More
                  </Button>
                </div>
              </div>
            </div>
          )}
          </div>
        </SheetBody>
      </SheetContent>
    </Sheet>
  );
}
